export const HEADER_NAME_API_TOKEN = 'x-api-key';
export const SCANOSS_GRPC_SERVICES_HOST = 'scanoss.com';
export const SCANOSS_GRPC_SERVICES_PORT = '443';

export const SCANOSS_GRPC_ENDPOINT =
  SCANOSS_GRPC_SERVICES_HOST + ':' + SCANOSS_GRPC_SERVICES_PORT;
