// ------ FILTERS SYNC WITH PYTHON CLIENT 06/10/2021 ------ //
import { FilterListType, FilterScope, FilterType, IFilter } from './Filtering';


export const defaultFilterForScanning: IFilter = {
  type: FilterListType.BANNED,
  filters: [
    { condition: '=', value: '0', ftype: FilterType.SIZE, scope: FilterScope.FILE },

    //Folders and files filters
    { condition: 'starts', value: '.', ftype: FilterType.NAME, scope: FilterScope.ALL },

    //Folder filters
    { condition: 'ends', value: '.egg-info', ftype: FilterType.NAME, scope: FilterScope.FOLDER },

    { condition: 'fullmatch', value: 'nbproject', ftype: FilterType.NAME, scope: FilterScope.FOLDER },
    { condition: 'fullmatch', value: 'nbbuild', ftype: FilterType.NAME, scope: FilterScope.FOLDER  },
    { condition: 'fullmatch', value: 'nbdist', ftype: FilterType.NAME, scope: FilterScope.FOLDER  },
    { condition: 'fullmatch', value: '__pycache__', ftype: FilterType.NAME, scope: FilterScope.FOLDER  },
    { condition: 'fullmatch', value: 'venv', ftype: FilterType.NAME, scope: FilterScope.FOLDER  },
    { condition: 'fullmatch', value: '_yardoc', ftype: FilterType.NAME, scope: FilterScope.FOLDER  },
    { condition: 'fullmatch', value: 'eggs', ftype: FilterType.NAME, scope: FilterScope.FOLDER  },
    { condition: 'fullmatch', value: 'wheels', ftype: FilterType.NAME, scope: FilterScope.FOLDER  },
    { condition: 'fullmatch', value: 'htmlcov', ftype: FilterType.NAME, scope: FilterScope.FOLDER  },
    { condition: 'fullmatch', value: '__pypackages__', ftype: FilterType.NAME, scope: FilterScope.FOLDER  },


    //Files filters

    { condition: 'fullmatch', value: 'gradlew', ftype: FilterType.NAME, scope: FilterScope.FILE },
    { condition: 'fullmatch', value: 'gradlew.bat', ftype: FilterType.NAME, scope: FilterScope.FILE },
    { condition: 'fullmatch', value: 'mvnw', ftype: FilterType.NAME, scope: FilterScope.FILE },
    { condition: 'fullmatch', value: 'mvnw.cmd', ftype: FilterType.NAME, scope: FilterScope.FILE },
    { condition: 'fullmatch', value: 'gradle-wrapper.jar', ftype: FilterType.NAME, scope: FilterScope.FILE },
    { condition: 'fullmatch', value: 'maven-wrapper.jar', ftype: FilterType.NAME, scope: FilterScope.FILE },
    { condition: 'fullmatch', value: 'thumbs.db', ftype: FilterType.NAME, scope: FilterScope.FILE },
    { condition: 'fullmatch', value: 'babel.config.js', ftype: FilterType.NAME, scope: FilterScope.FILE },
    { condition: 'fullmatch', value: 'license.txt', ftype: FilterType.NAME, scope: FilterScope.FILE },
    { condition: 'fullmatch', value: 'license.md', ftype: FilterType.NAME, scope: FilterScope.FILE },
    { condition: 'fullmatch', value: 'copying.lib', ftype: FilterType.NAME, scope: FilterScope.FILE },
    { condition: 'fullmatch', value: 'makefile', ftype: FilterType.NAME, scope: FilterScope.FILE },


    { condition: 'starts', value: '.asar', ftype: FilterType.NAME, scope: FilterScope.FILE },


    { condition: 'ends', value: 'news', ftype: FilterType.NAME, scope: FilterScope.FILE },
    { condition: 'ends', value: 'authors', ftype: FilterType.NAME, scope: FilterScope.FILE },


    { condition: 'ends', value: '-doc', ftype: FilterType.NAME, scope: FilterScope.FILE },
    { condition: 'ends', value: 'changelog', ftype: FilterType.NAME, scope: FilterScope.FILE },
    { condition: 'ends', value: 'config', ftype: FilterType.NAME, scope: FilterScope.FILE },
    { condition: 'ends', value: 'copying', ftype: FilterType.NAME, scope: FilterScope.FILE },
    { condition: 'ends', value: 'license', ftype: FilterType.NAME, scope: FilterScope.FILE },
    { condition: 'ends', value: 'licenses', ftype: FilterType.NAME, scope: FilterScope.FILE },
    { condition: 'ends', value: 'notice', ftype: FilterType.NAME, scope: FilterScope.FILE },
    { condition: 'ends', value: 'readme', ftype: FilterType.NAME, scope: FilterScope.FILE },
    { condition: 'ends', value: 'swiftdoc', ftype: FilterType.NAME, scope: FilterScope.FILE },
    { condition: 'ends', value: 'texidoc', ftype: FilterType.NAME, scope: FilterScope.FILE },
    { condition: 'ends', value: 'todo', ftype: FilterType.NAME, scope: FilterScope.FILE },
    { condition: 'ends', value: 'version', ftype: FilterType.NAME, scope: FilterScope.FILE },
    { condition: 'ends', value: 'ignore', ftype: FilterType.NAME, scope: FilterScope.FILE },
    { condition: 'ends', value: 'manifest', ftype: FilterType.NAME, scope: FilterScope.FILE },
    { condition: 'ends', value: 'sqlite', ftype: FilterType.NAME, scope: FilterScope.FILE },
    { condition: 'ends', value: 'sqlite3', ftype: FilterType.NAME, scope: FilterScope.FILE },

    { condition: '=', value: '.1', ftype: FilterType.EXTENSION, scope: FilterScope.FILE },
    { condition: '=', value: '.2', ftype: FilterType.EXTENSION, scope: FilterScope.FILE },
    { condition: '=', value: '.3', ftype: FilterType.EXTENSION, scope: FilterScope.FILE },
    { condition: '=', value: '.4', ftype: FilterType.EXTENSION, scope: FilterScope.FILE },
    { condition: '=', value: '.5', ftype: FilterType.EXTENSION, scope: FilterScope.FILE },
    { condition: '=', value: '.6', ftype: FilterType.EXTENSION, scope: FilterScope.FILE },
    { condition: '=', value: '.7', ftype: FilterType.EXTENSION, scope: FilterScope.FILE },
    { condition: '=', value: '.8', ftype: FilterType.EXTENSION, scope: FilterScope.FILE },
    { condition: '=', value: '.9', ftype: FilterType.EXTENSION, scope: FilterScope.FILE },
    { condition: '=', value: '.ac', ftype: FilterType.EXTENSION, scope: FilterScope.FILE },
    { condition: '=', value: '.adoc', ftype: FilterType.EXTENSION, scope: FilterScope.FILE },
    { condition: '=', value: '.am', ftype: FilterType.EXTENSION, scope: FilterScope.FILE },
    { condition: '=', value: '.asciidoc', ftype: FilterType.EXTENSION, scope: FilterScope.FILE },
    { condition: '=', value: '.bmp', ftype: FilterType.EXTENSION, scope: FilterScope.FILE },
    { condition: '=', value: '.build', ftype: FilterType.EXTENSION, scope: FilterScope.FILE },
    { condition: '=', value: '.cfg', ftype: FilterType.EXTENSION, scope: FilterScope.FILE },
    { condition: '=', value: '.chm', ftype: FilterType.EXTENSION, scope: FilterScope.FILE },
    { condition: '=', value: '.class', ftype: FilterType.EXTENSION, scope: FilterScope.FILE },
    { condition: '=', value: '.cmake', ftype: FilterType.EXTENSION, scope: FilterScope.FILE },
    { condition: '=', value: '.cnf', ftype: FilterType.EXTENSION, scope: FilterScope.FILE },
    { condition: '=', value: '.conf', ftype: FilterType.EXTENSION, scope: FilterScope.FILE },
    { condition: '=', value: '.config', ftype: FilterType.EXTENSION, scope: FilterScope.FILE },
    { condition: '=', value: '.contributors', ftype: FilterType.EXTENSION, scope: FilterScope.FILE },
    { condition: '=', value: '.copying', ftype: FilterType.EXTENSION, scope: FilterScope.FILE },
    { condition: '=', value: '.crt', ftype: FilterType.EXTENSION, scope: FilterScope.FILE },
    { condition: '=', value: '.csproj', ftype: FilterType.EXTENSION, scope: FilterScope.FILE },
    { condition: '=', value: '.css', ftype: FilterType.EXTENSION, scope: FilterScope.FILE },
    { condition: '=', value: '.csv', ftype: FilterType.EXTENSION, scope: FilterScope.FILE },
    { condition: '=', value: '.dat', ftype: FilterType.EXTENSION, scope: FilterScope.FILE },
    { condition: '=', value: '.data', ftype: FilterType.EXTENSION, scope: FilterScope.FILE },
    { condition: '=', value: '.doc', ftype: FilterType.EXTENSION, scope: FilterScope.FILE },
    { condition: '=', value: '.docx', ftype: FilterType.EXTENSION, scope: FilterScope.FILE },
    { condition: '=', value: '.dtd', ftype: FilterType.EXTENSION, scope: FilterScope.FILE },
    { condition: '=', value: '.dts', ftype: FilterType.EXTENSION, scope: FilterScope.FILE },
    { condition: '=', value: '.iws', ftype: FilterType.EXTENSION, scope: FilterScope.FILE },
    { condition: '=', value: '.c9', ftype: FilterType.EXTENSION, scope: FilterScope.FILE },
    { condition: '=', value: '.c9revisions', ftype: FilterType.EXTENSION, scope: FilterScope.FILE },
    { condition: '=', value: '.dtsi', ftype: FilterType.EXTENSION, scope: FilterScope.FILE },
    { condition: '=', value: '.dump', ftype: FilterType.EXTENSION, scope: FilterScope.FILE },
    { condition: '=', value: '.eot', ftype: FilterType.EXTENSION, scope: FilterScope.FILE },
    { condition: '=', value: '.eps', ftype: FilterType.EXTENSION, scope: FilterScope.FILE },
    { condition: '=', value: '.geojson', ftype: FilterType.EXTENSION, scope: FilterScope.FILE },
    { condition: '=', value: '.gdoc', ftype: FilterType.EXTENSION, scope: FilterScope.FILE },
    { condition: '=', value: '.gif', ftype: FilterType.EXTENSION, scope: FilterScope.FILE },
    { condition: '=', value: '.glif', ftype: FilterType.EXTENSION, scope: FilterScope.FILE },
    { condition: '=', value: '.gmo', ftype: FilterType.EXTENSION, scope: FilterScope.FILE },
    { condition: '=', value: '.gradle', ftype: FilterType.EXTENSION, scope: FilterScope.FILE },
    { condition: '=', value: '.guess', ftype: FilterType.EXTENSION, scope: FilterScope.FILE },
    { condition: '=', value: '.hex', ftype: FilterType.EXTENSION, scope: FilterScope.FILE },
    { condition: '=', value: '.htm', ftype: FilterType.EXTENSION, scope: FilterScope.FILE },
    { condition: '=', value: '.html', ftype: FilterType.EXTENSION, scope: FilterScope.FILE },
    { condition: '=', value: '.ico', ftype: FilterType.EXTENSION, scope: FilterScope.FILE },
    { condition: '=', value: '.iml', ftype: FilterType.EXTENSION, scope: FilterScope.FILE },
    { condition: '=', value: '.in', ftype: FilterType.EXTENSION, scope: FilterScope.FILE },
    { condition: '=', value: '.inc', ftype: FilterType.EXTENSION, scope: FilterScope.FILE },
    { condition: '=', value: '.info', ftype: FilterType.EXTENSION, scope: FilterScope.FILE },
    { condition: '=', value: '.ini', ftype: FilterType.EXTENSION, scope: FilterScope.FILE },
    { condition: '=', value: '.ipynb', ftype: FilterType.EXTENSION, scope: FilterScope.FILE },
    { condition: '=', value: '.jpeg', ftype: FilterType.EXTENSION, scope: FilterScope.FILE },
    { condition: '=', value: '.jpg', ftype: FilterType.EXTENSION, scope: FilterScope.FILE },
    { condition: '=', value: '.json', ftype: FilterType.EXTENSION, scope: FilterScope.FILE },
    { condition: '=', value: '.jsonld', ftype: FilterType.EXTENSION, scope: FilterScope.FILE },
    { condition: '=', value: '.lock', ftype: FilterType.EXTENSION, scope: FilterScope.FILE },
    { condition: '=', value: '.log', ftype: FilterType.EXTENSION, scope: FilterScope.FILE },
    { condition: '=', value: '.m4', ftype: FilterType.EXTENSION, scope: FilterScope.FILE },
    { condition: '=', value: '.map', ftype: FilterType.EXTENSION, scope: FilterScope.FILE },
    { condition: '=', value: '.markdown', ftype: FilterType.EXTENSION, scope: FilterScope.FILE },
    { condition: '=', value: '.md', ftype: FilterType.EXTENSION, scope: FilterScope.FILE },
    { condition: '=', value: '.md5', ftype: FilterType.EXTENSION, scope: FilterScope.FILE },
    { condition: '=', value: '.meta', ftype: FilterType.EXTENSION, scope: FilterScope.FILE },
    { condition: '=', value: '.mk', ftype: FilterType.EXTENSION, scope: FilterScope.FILE },
    { condition: '=', value: '.mxml', ftype: FilterType.EXTENSION, scope: FilterScope.FILE },
    { condition: '=', value: '.o', ftype: FilterType.EXTENSION, scope: FilterScope.FILE },
    { condition: '=', value: '.otf', ftype: FilterType.EXTENSION, scope: FilterScope.FILE },
    { condition: '=', value: '.out', ftype: FilterType.EXTENSION, scope: FilterScope.FILE },
    { condition: '=', value: '.pbtxt', ftype: FilterType.EXTENSION, scope: FilterScope.FILE },
    { condition: '=', value: '.pdf', ftype: FilterType.EXTENSION, scope: FilterScope.FILE },
    { condition: '=', value: '.pem', ftype: FilterType.EXTENSION, scope: FilterScope.FILE },
    { condition: '=', value: '.phtml', ftype: FilterType.EXTENSION, scope: FilterScope.FILE },
    { condition: '=', value: '.plist', ftype: FilterType.EXTENSION, scope: FilterScope.FILE },
    { condition: '=', value: '.png', ftype: FilterType.EXTENSION, scope: FilterScope.FILE },
    { condition: '=', value: '.po', ftype: FilterType.EXTENSION, scope: FilterScope.FILE },
    { condition: '=', value: '.ppt', ftype: FilterType.EXTENSION, scope: FilterScope.FILE },
    { condition: '=', value: '.prefs', ftype: FilterType.EXTENSION, scope: FilterScope.FILE },
    { condition: '=', value: '.properties', ftype: FilterType.EXTENSION, scope: FilterScope.FILE },
    { condition: '=', value: '.pyc', ftype: FilterType.EXTENSION, scope: FilterScope.FILE },
    { condition: '=', value: '.qdoc', ftype: FilterType.EXTENSION, scope: FilterScope.FILE },
    { condition: '=', value: '.result', ftype: FilterType.EXTENSION, scope: FilterScope.FILE },
    { condition: '=', value: '.rgb', ftype: FilterType.EXTENSION, scope: FilterScope.FILE },
    { condition: '=', value: '.rst', ftype: FilterType.EXTENSION, scope: FilterScope.FILE },
    { condition: '=', value: '.scss', ftype: FilterType.EXTENSION, scope: FilterScope.FILE },
    { condition: '=', value: '.sha', ftype: FilterType.EXTENSION, scope: FilterScope.FILE },
    { condition: '=', value: '.sha1', ftype: FilterType.EXTENSION, scope: FilterScope.FILE },
    { condition: '=', value: '.sha2', ftype: FilterType.EXTENSION, scope: FilterScope.FILE },
    { condition: '=', value: '.sha256', ftype: FilterType.EXTENSION, scope: FilterScope.FILE },
    { condition: '=', value: '.sln', ftype: FilterType.EXTENSION, scope: FilterScope.FILE },
    { condition: '=', value: '.spec', ftype: FilterType.EXTENSION, scope: FilterScope.FILE },
    { condition: '=', value: '.sql', ftype: FilterType.EXTENSION, scope: FilterScope.FILE },
    { condition: '=', value: '.sub', ftype: FilterType.EXTENSION, scope: FilterScope.FILE },
    { condition: '=', value: '.svg', ftype: FilterType.EXTENSION, scope: FilterScope.FILE },
    { condition: '=', value: '.svn-base', ftype: FilterType.EXTENSION, scope: FilterScope.FILE },
    { condition: '=', value: '.tab', ftype: FilterType.EXTENSION, scope: FilterScope.FILE },
    { condition: '=', value: '.template', ftype: FilterType.EXTENSION, scope: FilterScope.FILE },
    { condition: '=', value: '.test', ftype: FilterType.EXTENSION, scope: FilterScope.FILE },
    { condition: '=', value: '.tex', ftype: FilterType.EXTENSION, scope: FilterScope.FILE },
    { condition: '=', value: '.tiff', ftype: FilterType.EXTENSION, scope: FilterScope.FILE },
    { condition: '=', value: '.toml', ftype: FilterType.EXTENSION, scope: FilterScope.FILE },
    { condition: '=', value: '.ttf', ftype: FilterType.EXTENSION, scope: FilterScope.FILE },
    { condition: '=', value: '.txt', ftype: FilterType.EXTENSION, scope: FilterScope.FILE },
    { condition: '=', value: '.utf-8', ftype: FilterType.EXTENSION, scope: FilterScope.FILE },
    { condition: '=', value: '.vim', ftype: FilterType.EXTENSION, scope: FilterScope.FILE },
    { condition: '=', value: '.wav', ftype: FilterType.EXTENSION, scope: FilterScope.FILE },
    { condition: '=', value: '.woff', ftype: FilterType.EXTENSION, scope: FilterScope.FILE },
    { condition: '=', value: '.xht', ftype: FilterType.EXTENSION, scope: FilterScope.FILE },
    { condition: '=', value: '.xhtml', ftype: FilterType.EXTENSION, scope: FilterScope.FILE },
    { condition: '=', value: '.xls', ftype: FilterType.EXTENSION, scope: FilterScope.FILE },
    { condition: '=', value: '.xlsx', ftype: FilterType.EXTENSION, scope: FilterScope.FILE },
    { condition: '=', value: '.xml', ftype: FilterType.EXTENSION, scope: FilterScope.FILE },
    { condition: '=', value: '.xpm', ftype: FilterType.EXTENSION, scope: FilterScope.FILE },
    { condition: '=', value: '.xsd', ftype: FilterType.EXTENSION, scope: FilterScope.FILE },
    { condition: '=', value: '.xul', ftype: FilterType.EXTENSION, scope: FilterScope.FILE },
    { condition: '=', value: '.yaml', ftype: FilterType.EXTENSION, scope: FilterScope.FILE },
    { condition: '=', value: '.yml', ftype: FilterType.EXTENSION, scope: FilterScope.FILE },
    { condition: '=', value: '.wfp', ftype: FilterType.EXTENSION, scope: FilterScope.FILE },
    { condition: '=', value: '.editorconfig', ftype: FilterType.EXTENSION, scope: FilterScope.FILE },
    { condition: '=', value: '.dotcover', ftype: FilterType.EXTENSION, scope: FilterScope.FILE },
    { condition: '=', value: '.pid', ftype: FilterType.EXTENSION, scope: FilterScope.FILE },
    { condition: '=', value: '.lcov', ftype: FilterType.EXTENSION, scope: FilterScope.FILE },
    { condition: '=', value: '.egg', ftype: FilterType.EXTENSION, scope: FilterScope.FILE },
    { condition: '=', value: '.manifest', ftype: FilterType.EXTENSION, scope: FilterScope.FILE },
    { condition: '=', value: '.cache', ftype: FilterType.EXTENSION, scope: FilterScope.FILE },
    { condition: '=', value: '.coverage', ftype: FilterType.EXTENSION, scope: FilterScope.FILE },
    { condition: '=', value: '.cover', ftype: FilterType.EXTENSION, scope: FilterScope.FILE },
    { condition: '=', value: '.gem', ftype: FilterType.EXTENSION, scope: FilterScope.FILE },
    { condition: '=', value: '.lst', ftype: FilterType.EXTENSION, scope: FilterScope.FILE },
    { condition: '=', value: '.woff2', ftype: FilterType.EXTENSION, scope: FilterScope.FILE },
    { condition: '=', value: '.pickle', ftype: FilterType.EXTENSION, scope: FilterScope.FILE },
    { condition: '=', value: '.pdb', ftype: FilterType.EXTENSION, scope: FilterScope.FILE },
    { condition: '=', value: '.gml', ftype: FilterType.EXTENSION, scope: FilterScope.FILE },
    { condition: '=', value: '.pot', ftype: FilterType.EXTENSION, scope: FilterScope.FILE },
    { condition: '=', value: '.plt', ftype: FilterType.EXTENSION, scope: FilterScope.FILE },

  ],
};

